import http.server
import socketserver
from urllib.parse import urlparse
from urllib.parse import parse_qs

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()

        # Some custom HTML code, possibly generated by another function
        html = "<html><head></head><body>Healhy!</body></html>"
        self.wfile.write(bytes(html, "utf8"))

        return

while True:
    try:
        # Create an object of the above class
        handler_object = MyHttpRequestHandler

        PORT = 8080
        my_server = socketserver.TCPServer(("", PORT), handler_object)

        # Start the server
        my_server.serve_forever()
    except:
        print("Restarting health check webserver.")
